### ISSUE TITLE
sub help does not work

### ISSUE THREAD

**Issue by Menencia** [jdevera/sub#7]
otto is the sub name

```
$ otto
Usage: otto <command> [<args>]

A collection of commands

Traceback (most recent call last):
  File "/home/LucienS/otto/libexec/otto", line 813, in <module>
    sys.exit(main(sys.argv) or 0)
  File "/home/LucienS/otto/libexec/otto", line 758, in main
    ret = sub_help()
  File "/home/LucienS/otto/libexec/otto", line 513, in sub_help
    print_container_help(command_path, args)
  File "/home/LucienS/otto/libexec/otto", line 297, in print_container_help
    summaries = get_container_summaries(container)
  File "/home/LucienS/otto/libexec/otto", line 332, in get_container_summaries
    columns = int(subprocess.check_output(['tput', 'cols']))
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by Menencia** [comment]
I replaced L332 by : 

```
columns = int(subprocess.check_output(['stty', 'size']).split()[1])
```

and it worked

**Comment by jdevera** [comment]
Thanks, `stty size` should be more *universal*. Thanks, I'll change that too!
